### ISSUE TITLE
Is there Badge Available !

### ISSUE THREAD

**Issue by deshario** [ashazar/tab-drawer#2]
Hi Sir ! I like this lib very much but am searching for something like badge to set in tab for showing something like unread messages. can i do that please let me know #thankyou

**Comment by ashazar** [comment]
Hi @deshario 
With the current version, you cannot do unfortunately.
But i will try to update it with badges in a few days.

**Comment by deshario** [comment]
Thankx for superb lib. I'll do waiting 4 updates.

**Comment by ashazar** [comment]
You need to change TabDrawer's version to 1.2.0  in your build.gradle file.

You can read the details of using badges in README; under `v. 1.2.0 Release Notes:`

**Comment by deshario** [comment]
Thanks a lot for amazing library. 
I hope you would add new features in upcoming updates.
