### ISSUE TITLE
Set Margin or Padding For TabListItem !

### ISSUE THREAD

**Issue by sangei** [ashazar/tab-drawer#4]
Can we set margin or padding for TabListItem(Sub Items of Tab).
![screenshot_1509177183](https://user-images.githubusercontent.com/33173402/32132568-09c422f2-bbf0-11e7-9992-fc6b7664341f.png)

**Comment by ashazar** [comment]
Yes, you can do it via using a Custom Drawer ListItem Layout.
You can find the example below.

Bear in mind that your custom layout's Root Layout should be `RelativeLayout`, and the id of TextView (for the title) shoud be `list_item_title`, and id of the ImageView (for the icon) should be `list_item_img`.

Here is an example of the Custom Drawer ListItem Layout. (Let's name it `tab_list_item.xml`)
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="5dp" ---> You can add margin <---
        android:padding="5dp"                 ---> or padding <---
        android:gravity="center_vertical|start"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/list_item_img"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:contentDescription="@string/item_logo" />

        <TextView
            android:id="@+id/list_item_title"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center_vertical|start"
            android:padding="3dp"
            android:layout_marginLeft="10dp"
            android:layout_marginStart="10dp" />

    </LinearLayout>
</RelativeLayout>
```

In your activity, when you are defining TabDrawerData, you simply add 
`.setCustomDrawerListItemLayoutResourceId(R.layout.tab_list_item)`

And you are done.
